### ISSUE TITLE
Проблема при сборке backend. Не найден entrypoint.sh

### ISSUE THREAD

**Issue by AndreyGrand** [cu3blukekc/SwampHub#3]
Фрагмент лога сборки backend  командой docker-compose up --build backend
Выполняется под Windows из консоли git-bash. Из консоли CMD результат аналогичный.
Docker Compose version v2.24.5-desktop.1

 => [backend build  1/10] FROM docker.io/library/node:20-alpine@sha256:2f46fd49c767554c089a5eb219115313b72748d8f62f5eccb58ef52bc36db4ad                                                                    0.0s
 => CACHED [backend build  2/10] WORKDIR /dochub                                                                                                                                                           0.0s
 => CACHED [backend build  3/10] RUN npm install -g recursive-install                                                                                                                                      0.0s
 => CACHED [backend build  4/10] COPY ./dochub/package.json /dochub/package.json                                                                                                                           0.0s
 => CACHED [backend build  5/10] COPY ./dochub/package-lock.json /dochub/package-lock.json                                                                                                                 0.0s
 => CACHED [backend pre 3/4] COPY dochub/plugins /docker-context/dochub/plugins                                                                                                                            0.0s
 => CACHED [backend pre 4/4] RUN cd /docker-context/;     find dochub/plugins -name "package.json" -mindepth 0 -maxdepth 4 -exec cp --parents "{}" / ;                                                     0.0s
 => CACHED [backend build  6/10] COPY --from=pre /dochub/ /dochub/                                                                                                                                         0.0s
 => CACHED [backend build  7/10] RUN cd /dochub/plugins && npx recursive-install --skip-root                                                                                                               0.0s
 => CACHED [backend build  8/10] RUN npm install                                                                                                                                                           0.0s
 => CACHED [backend build  9/10] COPY ./dochub /dochub/                                                                                                                                                    0.0s
 => CACHED [backend build 10/10] RUN npm run backend-build                                                                                                                                                 0.0s
 => CACHED [backend prod  9/12] COPY --from=build /dochub/src ./src                                                                                                                                        0.0s
 => CACHED [backend prod 10/12] COPY --from=build /dochub/dist ./dist                                                                                                                                      0.0s
 => CACHED [backend prod 11/12] COPY --from=build /dochub/public ./public                                                                                                                                  0.0s
 => CACHED [backend prod 12/12] COPY ./entrypoint.sh /entrypoint.sh                                                                                                                                        0.0s
 => [backend] exporting to image                                                                                                                                                                           0.0s
 => => exporting layers                                                                                                                                                                                    0.0s
 => => writing image sha256:28a7975108bc5fc885a00a68afbea319420e92e34a14aa0831b86a676430e2ad                                                                                                               0.0s
 => => naming to docker.io/library/swamphub-backend                                                                                                                                                        0.0s
[+] Running 3/0
 ✔ Container swamphub-metamodel-1  Running                                                                                                                                                                 0.0s
 ✔ Container swamphub-manifest-1   Running                                                                                                                                                                 0.0s
 ✔ Container swamphub-backend-1    Created                                                                                                                                                                 0.0s
Attaching to backend-1
backend-1  | exec /entrypoint.sh: no such file or directory
backend-1 exited with code 1

**Comment by ValentinKozlov** [comment]
Так как у Саши нет винды, то я тестировал на своей.
Windows 11
Docker Desktop 4.27.2 (137060)
Docker Compose version v2.24.5-desktop.1

Какие проблемы были обнаружены:
1.	При попытке выполнить команду git clone --recurse-submodules https://github.com/cu3blukekc/SwampHub.git минут через 20-25 клонирование отвалилось (к сожалению ошибку не скопировал). Пробежавшись по папкам содержащим сабмодули, обнаружил что данных нет (см. файл .gitmodules).
2.	Снова все удалил и пошел вторым путем используя git bash:
•	git clone https://github.com/cu3blukekc/SwampHub.git
user MINGW64 ~/OneDrive/Git/DocHub_impl
$ git clone https://github.com/cu3blukekc/SwampHub.git
Cloning into 'SwampHub'...
remote: Enumerating objects: 354, done.
remote: Counting objects: 100% (354/354), done.
remote: Compressing objects: 100% (241/241), done.
remote: Total 354 (delta 120), reused 299 (delta 68), pack-reused 0
Receiving objects: 100% (354/354), 8.61 MiB | 1.12 MiB/s, done.
Resolving deltas: 100% (120/120), done.
•	git submodule init
Submodule 'backend/dochub' (https://github.com/RabotaRu/DocHub.git) registered for path 'backend/dochub'
Submodule 'frontend/dochub' (https://github.com/RabotaRu/DocHub.git) registered for path 'frontend/dochub'
Submodule 'manifest/manifest' (https://github.com/ValentinKozlov/DocHubExampleManifest.git) registered for path 'manifest/manifest'
Submodule 'metamodel/metamodel' (https://github.com/ValentinKozlov/DocHubExampleMetamodel.git) registered for path 'metamodel/metamodel'
Submodule 'plantuml-server' (https://github.com/vlad-markin/plantuml-server.git) registered for path 'plantuml'
•	git submodule update – отвалился с ошибкой:
$ git submodule update
Cloning into 'C:/Users/user/OneDrive/Git/DocHub_impl/SwampHub/backend/dochub'...
error: 6663 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
fatal: clone of 'https://github.com/RabotaRu/DocHub.git' into submodule path 'C:/Users/i_fro/OneDrive/Git/DocHub_impl/SwampHub/backend/dochub' failed
Failed to clone 'backend/dochub'. Retry scheduled

3.	Снова все удалил и выполнил пункт 2 используя powershell – все отработало нормально
4.	Дальше выполнил команду docker compose up -–build
Все контейнеры поднялись. Дальше можно пробовать поднимать компоненты отдельно.

**Вывод:**
Сборка контейнеров на винде видимо зависит от shell на котором собирается контейнер. Так как bash это линуксовый шел, то рекомендуется при сборке использовать виндовый (powershell). А вообще лучше не использовать винду для разработки если это только не C#.

**Comment by AndreyGrand** [comment]
спасибо, буду пробовать сpowershell. В остальном наш опыт совпал
